### ISSUE TITLE
float coloring for float capped skins

### ISSUE THREAD

**Issue by GrueseGehenRaus** [GODrums/BetterFloat#107]
I'm not sure what is causing this issue. If float capped skins are not handled correctly or if the calculation doesn't work well with skins that have limited supply but I do think 0.61 should be green instead of red.
![image](https://github.com/user-attachments/assets/05d18d2e-f961-45fd-b249-3bff7a5ff469)
![image](https://github.com/user-attachments/assets/33deaf58-a694-43d7-bdc6-f1e2b11db175)

**Comment by GODrums** [comment]
Floats are a very delicate topic and there are many interpretations on what a "good" or "bad" float is. I highly doubt anybody would ever consider 0.0615 a good float though, it's not even in the top 15% of possible FN values.

Buff's system is probably the most common one, but deviation-based approaches would statistically be more accurate. The extension currently uses a mixture of both (with varying success admittedly).
I agree with you that currently custom float ranges are not handled accordingly, I'll try to come up with a better approach.

**Comment by GODrums** [comment]
Pushed a reworked algorithm in [b858c91](https://github.com/GODrums/BetterFloat/commit/b858c91e5d328fc44bdb2d3e3c7ef2864dbdda54).
From my testing it should much better encapsulate custom float limits. Will be included in the next version `2.8.0`, which should drop later this week.
