### ISSUE TITLE
SP an buff prices arent working

### ISSUE THREAD

**Issue by fasfager** [GODrums/BetterFloat#108]
I downloaded the extension for Google Chrome and the prices do not appear and the sticker price button works the other way around
![image](https://github.com/user-attachments/assets/7ee26b73-1f2e-4ade-8c5f-0e086947b045)
![image](https://github.com/user-attachments/assets/5b4a0206-72f5-4a86-89ca-e2cbab8a2c24)
![image](https://github.com/user-attachments/assets/897907af-c815-4ed4-978e-64680dac7db3)

**Comment by GODrums** [comment]
I assume you already found a solution to the problem on your own?

**Comment by fasfager** [comment]
> I assume you already found a solution to the problem on your own?

somehow it worked after a while
