### ISSUE TITLE
CSFloat: High/Low float coloring

### ISSUE THREAD

**Issue by GODrums** [GODrums/BetterFloat#4]
Make it easier to see if an item is of low or high float(e.g. 2x 0).

This feature already exists for Skinport and could similarly be converted to CSFloat and Skinbid.

Example of how this looks on Skinport:
![Image](https://github.com/GODrums/BetterFloat/assets/21990230/05a394dc-7932-436e-a2f5-b00decfca286)

Edge case handling (also missing on Skinport):
- float caps need to be handled accordingly, e.g. if an item uses float values [0;0.08] the values [0.07;0.08] should, of course, be colored as bad instead of good (low MW).

**Comment by bycop** [comment]
- [x] Csfloat https://github.com/GODrums/BetterFloat/pull/35 To be merged
- [ ] Skinbin
