### ISSUE TITLE
is skinport price to buff price ratio a thing?

### ISSUE THREAD

**Issue by rzrv** [GODrums/BetterFloat#41]
Hi is there a way to enable skinport price to buff price ratio similar to the option for csfloat?

![image](https://github.com/GODrums/BetterFloat/assets/103303086/cf7e79a1-077f-4be1-87f5-bf9be3bed549)

**Comment by GODrums** [comment]
Hey, such a setting does not exist yet.
If you know how to code, feel free to contribute it.
Otherwise I'll put it onto the [project board](https://github.com/users/GODrums/projects/1) and hopefully we can get to it at some point in the future.

**Comment by rzrv** [comment]
> Hey, such a setting does not exist yet. If you know how to code, feel free to contribute it. Otherwise I'll put it onto the [project board](https://github.com/users/GODrums/projects/1) and hopefully we can get to it at some point in the future.

Wow fast response! Not the greatest coder atm so i'm not much help there. No rush for the addition im good with quick math anyways. :)

**Comment by GODrums** [comment]
Done in commit [abdf126](https://github.com/GODrums/BetterFloat/commit/abdf126ce07d5ce7a9d5861b2254da1498c1aba7). Will be included in the next release

**Comment by GODrums** [comment]
Now live in version `1.14.3`
