### ISSUE TITLE
Price difference currency doesn't update to euros.

### ISSUE THREAD

**Issue by STheoo** [GODrums/BetterFloat#77]
When using csfloat in euros the price difference displayed by betterfloat is in usd.
![sdsd](https://github.com/GODrums/BetterFloat/assets/46623018/15ea725b-c304-4a1b-a65b-12ed64c0ea39)

**Comment by GODrums** [comment]
Thank you for reporting this bug!

It has been fixed with commit 8729b05 and will release in update ` 2.1.4`.
